SD: Code for Issue 23.
ucsb-cs48-w19/5pm-ucsb-rideshare pull request #29
Opened 2019-02-01 20:32 UTC by SamuelDunn

2019-02-01 22:56 UTC, SamuelDunn commented
This PR is for issue #23
From the rideshare_app directory the app can be run by typing "nodemon" into the console. The homepage will be displayed at localhost:5000.

2019-02-02 02:40 UTC, scottpchow23 requested changes
You need to gitignore the node modules directory.

2019-02-02 08:51 UTC, SamuelDunn commented
All node_module files are ignored now.

2019-02-04 23:54 UTC, scottpchow23 approved these changes

2019-02-04 23:59 UTC, merged